---
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - devNet

  db:
    image: postgres:14
    restart: always
    container_name: postgres
    expose:
      - 5432
    ports:
      - "6500:5432"
    environment:
      PGUSER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h postgres"
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - devNet

volumes:
  postgres-db:

networks:
  devNet:
