---
version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
volumes:
  postgres-db: