# TOKEN_LIFETIME FORMAT - Days:Hours:Minutes
JWT_LIFETIME = '0:1:0'
JWT_SECRET = 'SOME_REALLY_SECRET_INFO'
JWT_ALGORITHM = 'HS512'
JWT_EXP_DATE_FORMAT = '%Y/%m/%d %H:%M'
YANDEX_GEOCODER_API_KEY = NotImplemented
