# TOKEN_LIFETIME FORMAT - Days:Hours:Minutes
JWT_LIFETIME = '0:1:0'
JWT_SECRET = 'SOME_REALLY_SECRET_INFO'
JWT_ALGORITHM = 'HS512'
JWT_EXP_DATE_FORMAT = '%Y/%m/%d %H:%M'
YANDEX_GEOCODER_API_KEY = NotImplemented
GEOAPIFY_API_KEY = NotImplemented
OPEN_ROUTE_SERVICE_API_KEY = NotImplemented
POSTGRES_PASSWORD = 'pass'
POSTGRES_USER = 'user'
POSTGRES_DB = 'db'
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = 6500
REDIS_HOST = 'redis'
REDIS_PORT = 6379
REDIS_DB = 0
